version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      aVMneEr2U+54BfHbJj6lvbOo6pfsRkfvro90mjV5UMRO9/Y+W7Kpdn+DA9MtESUxpZ1b7LTstFgrznryGqMAU2goKHfxrrN9dHAUpXcFAjI1tDFzhfeQP7LUQQz/REzrAxOo/L3ecsYm2MgAyVWs5fOpxRapDi07FdN6z/WKL3s=
